// Generated by https://pagedraw.io/pages/11698
import React from 'react';
import './bloglink.css';


export default class Bloglink extends React.Component {
  render() {
    return (
      <div className="pd-onhover-parent bloglink">
          <div className="pd-onhover bloglink-default_hover-0">
              <div className="bloglink-0-0">
                  <div className="bloglink-link_-0">{ this.props.text }</div>
              </div>
          </div>
          { (("default") === "default") ?
              <div className="bloglink-default-8">
                  <div className="bloglink-1-0-0">
                      <div className="bloglink-link_-8">{ this.props.text }</div>
                  </div>
              </div>
          : null}
      </div>
    );
  }
};
