// Generated by https://pagedraw.io/pages/11698
import React from 'react';
import './default_hover.css';


function render() {
    return <div className="default_hover-default_hover-1">
        <div className="default_hover-0">
            <div className="default_hover-link_-9">
                { this.props.text }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
