// Generated by https://pagedraw.io/pages/11698
import React from 'react';
import Referencelink from './referencelink';
import Bloglink from './bloglink';
import Navigationlink from './navigationlink';
import './main.css';
import ReactPlayer from 'react-player'
import Iframe from 'react-iframe'

export default class Main extends React.Component {
  render() {
    return (
      <div className="main">
          <div className="main-mobile-7">
              <div className="main-0-0">
                  <div className="main-marcus_-5">Marcus</div>
              </div>
              <div className="main-0-1">
                  <div className="main-hero-image-9">
                      <div className="main-0-1-0-0">
                          <div className="main-rectangle-4">
                              <div className="main-0-1-0-0-0-0">
                                  <div className="main-marcus_ellison_-6">
                                      Marcus Ellison
                                  </div>
                              </div>
                              <div className="main-0-1-0-0-0-1">
                                  <div className="main-entrepreneur_maker_coder_-7">
                                      <div>Entrepreneur</div>
                                      <div>Maker</div>
                                      <div>Coder </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="main-0-1-0-1" /> 
                  </div>
              </div>
              <div className="main-0-2">
                  <div className="main-rectangle-9">
                      <div className="main-0-2-0-0">
                          <div className="main-why_-4">WHY</div>
                      </div>
                      <div className="main-0-2-0-1">
                          <div className="main-life_has_a_purpose_you_are_that_purpose_-7">
                              Life has a purpose. You are that purpose. 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-0-3">
                  <div className="main-rectangle-1">
                      <div className="main-0-3-0-0">
                          <div className="main-work-image-5">
                              <div className="main-0-3-0-0-0-0">
                                  <div className="main-in_stealth_-0">In Stealth</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-0-4">
                  <div className="main-rectangle-17">
                      <div className="main-0-4-0-0">
                          <div className="main-venturemark_-1">VentureMark</div>
                      </div>
                      <div className="main-0-4-0-1">
                          <div className="main-founder_ceo_product_development_-8">
                              {"FOUNDER | CEO  | PRODUCT & DEVELOPMENT"}
                          </div>
                      </div>
                      <div className="main-0-4-0-2">
                          <div className="main-in_private_beta_venturemark_organizes_investments_and_relationships_for_angel_investors_around_the_world_no_data_entry_required_-3">
                              In private beta. VentureMark organizes investments and relationships for angel investors around the world. No data entry required.
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-0-5">
                  <div className="main-rectangle-5">
                      <div className="main-0-5-0-0">
                          <div className="main-work-image-7" /> 
                      </div>
                  </div>
              </div>
              <div className="main-0-6">
                  <div className="main-rectangle-50">
                      <div className="main-0-6-0-0">
                          <div className="main-hackerfleet_-8">HackerFleet</div>
                      </div>
                      <div className="main-0-6-0-1">
                          <div className="main-co-founder_ceo_-2">
                              {"CO-FOUNDER | CEO"}
                          </div>
                      </div>
                      <div className="main-0-6-0-2">
                          <div className="main-innovation_studio_in_vietnam_profitable_within_3">
                              Innovation studio in Vietnam. Profitable within 3 months. We held two events per month on product innovation and helped companies solve tech and product challenges in Singapore, Vietnam and San Francisco.
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-0-7">
                  <div className="main-rectangle-3">
                      <div className="main-0-7-0-0">
                          <div className="main-work-image-2" /> 
                      </div>
                  </div>
              </div>
              <div className="main-0-8">
                  <div className="main-rectangle-7">
                      <div className="main-0-8-0-0">
                          <div className="main-coderschool_-2">CoderSchool</div>
                      </div>
                      <div className="main-0-8-0-1">
                          <div className="main-co-founder_business_development_-5">
                              {"CO-FOUNDER |  BUSINESS DEVELOPMENT"}
                          </div>
                      </div>
                      <div className="main-0-8-0-2">
                          <div className="main-coding_school_in_vietnam_grew_community_reaching_thousands_of_engineers_and_dozens_of_companies_negotiated_and_closed_first_4">
                              Coding school in Vietnam. Grew community reaching thousands of engineers and dozens of companies. Negotiated and closed first $40,000 in revenue. Created and managed pre-accelerator pilot program.
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-0-9">
                  <div className="main-rectangle-16">
                      <div className="main-0-9-0-0">
                          <div className="main-work-image-0" /> 
                      </div>
                  </div>
              </div>
              <div className="main-0-10">
                  <div className="main-rectangle-59">
                      <div className="main-0-10-0-0">
                          <div className="main-wurk_happy_-5">Wurk Happy</div>
                      </div>
                      <div className="main-0-10-0-1">
                          <div className="main-co-founder_ceo_product_development_-3">
                              {"CO-FOUNDER |  CEO | PRODUCT &  DEVELOPMENT"}
                          </div>
                      </div>
                      <div className="main-0-10-0-2">
                          <div className="main-b2">
                              B2B SaaS for freelancers. Raised $140k angel. Users could create agreements, invoice, receive payment, and deposit funds securely into their bank account in a simple interface.
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-0-11">
                  <div className="main-rectangle-46">
                      <div className="main-0-11-0-0">
                          <div className="main-work-image-1" /> 
                      </div>
                  </div>
              </div>
              <div className="main-0-12">
                  <div className="main-rectangle-0">
                      <div className="main-0-12-0-0">
                          <div className="main-saulter_ellison_-3">
                              {"Saulter & Ellison"}
                          </div>
                      </div>
                      <div className="main-0-12-0-1">
                          <div className="main-co-founder_-2">CO-FOUNDER </div>
                      </div>
                      <div className="main-0-12-0-2">
                          <div className="main-syndicated_commercial_real_estate_opportunities_in_new_york_city_with_anthony_leichter_and_axel_stawski_we_got_a_2">
                              Syndicated Commercial Real Estate Opportunities in New York City with Anthony Leichter and Axel Stawski. We got a $20 million opportunity under contract and secured funds for acquisition and development.
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-0-13">
                  <div className="main-rectangle_8">
                      <div className="main-0-13-0-0">
                          <div className="main-speaking_-7">SPEAKING</div>
                      </div>
                      <div className="main-0-13-0-1">
                          <div className="main-philippines_interview-7" /> 
                      </div>
                      <div className="main-0-13-0-2">
                          <div className="main-philippines_-1">Philippines</div>
                      </div>
                      <div className="main-0-13-0-3">
                          <div className="main-philippines_interview-2" /> 
                      </div>
                      <div className="main-0-13-0-4">
                          <div className="main-_singapore_-3"> Singapore</div>
                      </div>
                      <div className="main-0-13-0-5">
                          <div className="main-philippines_interview-5" /> 
                      </div>
                      <div className="main-0-13-0-6">
                          <div className="main-vietnam_-5">Vietnam</div>
                      </div>
                  </div>
              </div>
              <div className="main-0-14">
                  <div className="main-0-14-0" /> 
                  <div className="main-rectangle_6">
                      <div className="main-0-14-1-0">
                          <div className="main-references_-8">REFERENCES</div>
                      </div>
                      <div className="main-0-14-1-1">
                          <div className="main-_marcus_and_i_went_to_nyu_together_he_s_a_super_smart_entrepreneur_with_big_ideas_and_fine_execution_i_often_believe_in_backing_people_over_ideas_marcus_is_a_perfect_example_of_the_type_of_person_i_would_back_even_without_an_idea_-2">
                              {"\" Marcus and I went to NYU together. He's a super smart entrepreneur with big ideas and fine execution. I often believe in backing people over ideas. Marcus is a perfect example of the type of person I would back (even without an idea)! \" "}
                          </div>
                      </div>
                      <div className="main-0-14-1-2">
                          <a href="https://www.linkedin.com/in/brycemaddock/" target="_blank" className="main-0-14-1-2-0">
                              <div className="main-bryce_maddock_-2">BRYCE MADDOCK</div>
                          </a>
                      </div>
                      <div className="main-0-14-1-3">
                          <div className="main-0-14-1-3-0">
                              <div className="main-0-14-1-3-0-0">
                                  <div className="main-ceo_co-founder_-8">
                                      {"CEO | Co-Founder, "}
                                  </div>
                              </div>
                          </div>
                          <a href="https://www.taskus.com/" target="_blank" className="main-0-14-1-3-1">
                              <div className="main-referencelink_instance-6">
                                  <Referencelink text={"TaskUs"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-4">
                          <div className="main-referencelink_instance-2">
                              <Referencelink text={"Valued at over $500M "} /> 
                          </div>
                      </div>
                      <div className="main-0-14-1-5">
                          <div className="main-_marcus_is_a_thoughtful_collaborator_a_philosopher_in_developer_s_shoes_he_strives_to_understand_the_undercurrents_of_what_he_makes_a_key_component_to_creating_things_full_of_meaning_working_with_him_is_a_joy_-5">
                              {"\"Marcus is a thoughtful collaborator—a philosopher in developer's shoes. He strives to understand the undercurrents of what he makes, a key component to creating things full of meaning. Working with him is a joy.\""}
                          </div>
                      </div>
                      <div className="main-0-14-1-6">
                          <a href="https://www.linkedin.com/in/joeycofone/" target="_blank" className="main-0-14-1-6-0">
                              <div className="main-joey_cofone_-9">JOEY COFONE</div>
                          </a>
                      </div>
                      <div className="main-0-14-1-7">
                          <div className="main-0-14-1-7-0">
                              <div className="main-0-14-1-7-0-0">
                                  <div className="main-ceo_co-founder_-5">
                                      {"CEO | Co-Founder,"}
                                  </div>
                              </div>
                          </div>
                          <a href="https://www.baronfig.com/" target="_blank" className="main-0-14-1-7-1">
                              <div className="main-referencelink_instance-5">
                                  <Referencelink text={"Baron Fig"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-8">
                          <a href="http://joeycofone.com/about/" target="_blank" className="main-0-14-1-8-0">
                              <div className="main-referencelink_instance-0">
                                  <Referencelink text={"Award winning designer"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-9">
                          <div className="main-_marcus_is_a_fellow_startup_founder_i_ve_met_with_a_few_times_in_nyc_who_is_serious_determined_and_extremely_smart_i_ve_watched_him_build_up_wurk_happy_from_idea_stage_to_design_mockup_to_product_and_he_knows_how_to_get_things_done_-0">
                              {"\"Marcus is a fellow startup founder I've met with a few times in NYC who is serious, determined, and extremely smart. I've watched him build up Wurk Happy from idea stage to design mockup to product, and he knows how to get things done\""}
                          </div>
                      </div>
                      <div className="main-0-14-1-10">
                          <a href="https://www.linkedin.com/in/andrewmontalenti/" target="_blank" className="main-0-14-1-10-0">
                              <div className="main-andrew_montalenti_-4">
                                  ANDREW MONTALENTI
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-11">
                          <div className="main-0-14-1-11-0">
                              <div className="main-0-14-1-11-0-0">
                                  <div className="main-cto_co-founder_-4">
                                      {"CTO | Co-Founder, "}
                                  </div>
                              </div>
                          </div>
                          <a href="https://www.parse.ly/" target="_blank" className="main-0-14-1-11-1">
                              <div className="main-referencelink_instance-9">
                                  <Referencelink text={"Parse.ly"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-12">
                          <a href="https://blog.parse.ly/post/6282/why-we-said-no-vc-money/" target="_blank" className="main-0-14-1-12-0">
                              <div className="main-referencelink_instance-69">
                                  <Referencelink text={"Turned down $40 million investment offer"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-13">
                          <div className="main-_amazing_and_large_underserved_space_that_needs_better_aggregation_platforms_and_technology_marcus_and_team_wurk_happy_are_winners_and_the_technical_talent_is_also_strong_looking_forward_to_their_inevitable_sucess_with_the_correct_financial_partners_-6">
                              {"\"Amazing and large underserved space that needs better aggregation platforms and technology. Marcus and team [Wurk Happy] are winners and the technical talent is also strong. Looking forward to their inevitable sucess with the correct financial partners....\""}
                          </div>
                      </div>
                      <div className="main-0-14-1-14">
                          <a href="https://www.linkedin.com/in/davidolk/" target="_blank" className="main-0-14-1-14-0">
                              <div className="main-david_olk_-8">DAVID OLK</div>
                          </a>
                      </div>
                      <div className="main-0-14-1-15">
                          <div className="main-0-14-1-15-0">
                              <div className="main-0-14-1-15-0-0">
                                  <div className="main-coo_co-founder_-0">
                                      {"COO | Co-Founder,"}
                                  </div>
                              </div>
                          </div>
                          <a href="https://www.shopkeep.com/" target="_blank" className="main-0-14-1-15-1">
                              <div className="main-referencelink_instance-55">
                                  <Referencelink text={"ShopKeep"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-16">
                          <a href="https://venturebeat.com/2015/07/28/shopkeep-focuses-on-growth-with-60-million-in-series-d-funding/" target="_blank" className="main-0-14-1-16-0">
                              <div className="main-referencelink_instance-58">
                                  <Referencelink text={"Raised over $100M"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-17">
                          <div className="main-_working_with_marcus_is_always_a_pleasure_as_he_is_an_engineer_who_builds_things_from_first_principles_when_they_are_truly_needed_and_doesn_t_get_carried_away_with_the_current_fads_plus_he_s_just_a_genuinely_nice_guy_-0">
                              {"\"Working with Marcus is always a pleasure as he is an engineer who builds things from first principles when they are truly needed, and doesn’t get carried away with the current fads. Plus, he’s just a genuinely nice guy.\""}
                          </div>
                      </div>
                      <div className="main-0-14-1-18">
                          <a href="https://www.linkedin.com/in/theodorewyly/" target="_blank" className="main-0-14-1-18-0">
                              <div className="main-teddy_wyly_-6">TEDDY WYLY</div>
                          </a>
                      </div>
                      <div className="main-0-14-1-19">
                          <div className="main-0-14-1-19-0">
                              <div className="main-0-14-1-19-0-0">
                                  <div className="main-software_engineer_-3">
                                      Software Engineer,
                                  </div>
                              </div>
                          </div>
                          <a href="https://www.apple.com/" target="_blank" className="main-0-14-1-19-1">
                              <div className="main-referencelink_instance-1">
                                  <Referencelink text={"Apple"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-20">
                          <div className="main-writing_-0">WRITING</div>
                      </div>
                      <div className="main-0-14-1-21">
                          <a href="https://medium.com/venturemark/wework-southeast-asia-3c5870433a9c" target="_blank" className="main-0-14-1-21-0">
                              <div className="main-bloglink_instance-0">
                                  <Bloglink text={"Disruption of ASEAN Real Estate"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-22">
                          <a href="https://blog.hackerfleet.com/how-the-worlds-best-companies-build-new-products-dc4092300689" target="_blank" className="main-0-14-1-22-0">
                              <div className="main-bloglink_instance-5">
                                  <Bloglink text={"How to Build New Products"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-23">
                          <a href="https://medium.com/venturemark/broken-5985e175ae62" target="_blank" className="main-0-14-1-23-0">
                              <div className="main-bloglink_instance-8">
                                  <Bloglink text={"Investing in Southeast Asian Startups"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-0-14-1-24">
                          <div className="main-bloglink_instance-83">
                              <Bloglink text={"Dear Young Talent"} /> 
                          </div>
                      </div>
                      <div className="main-0-14-1-25">
                          <div className="main-contact_-8">CONTACT</div>
                      </div>
                      <div className="main-0-14-1-26">
                          <div className="main-please_contact_me_if_you_are_exceptional_or_strive_to_be_-1">
                              Please contact me if you are exceptional. Or strive to be.
                          </div>
                      </div>
                      <div className="main-0-14-1-27">
                          <div className="main-marcus_dot_ellison_at_gmail_dot_com_-2">
                              {"marcus [dot] ellison [at] gmail [dot] com"}
                          </div>
                      </div>
                  </div>
                  <div className="main-0-14-2" /> 
              </div>
              <div className="main-0-15">
                  <div className="main-line_2" /> 
              </div>
              <div className="main-0-16">
                  <div className="main-rectangle_7">
                      <div className="main-0-16-0-0">
                          <div className="main-marcus_ellison_-5">
                              Marcus Ellison
                          </div>
                      </div>
                      <div className="main-0-16-0-1">
                          <div className="main-globally_crafted_copyright_2">
                              Globally crafted. Copyright 2018.
                          </div>
                      </div>
                      <div className="main-0-16-0-2">
                          <a href="https://www.producthunt.com/@marcojelli" target="_blank" className="main-0-16-0-2-0">
                              <div className="main-image-0" /> 
                          </a>
                          <a href="https://twitter.com/marcojelli" target="_blank" className="main-0-16-0-2-1">
                              <div className="main-image-2" /> 
                          </a>
                          <a href="https://github.com/marcusellison" target="_blank" className="main-0-16-0-2-2">
                              <div className="main-image-9" /> 
                          </a>
                          <a href="https://www.linkedin.com/in/marcusellison/" target="_blank" className="main-0-16-0-2-3">
                              <div className="main-image-7" /> 
                          </a>
                          <a href="https://example.cohttps://www.instagram.com/sixwordsofpoetrym" target="_blank" className="main-0-16-0-2-4">
                              <div className="main-image-3" /> 
                          </a>
                      </div>
                  </div>
              </div>
          </div>
          <div className="main-desktop-9">
              <div className="main-1-0">
                  <div className="main-marcus_-1">Marcus</div>
                  <div className="main-1-0-1">
                      <div className="main-1-0-1-0">
                          <div className="main-homeanchor-5"><div id="home" /></div>
                      </div>
                  </div>
                  <div className="main-1-0-2" /> 
                  <div className="main-1-0-3">
                      <div className="main-1-0-3-0">
                          <a href="#home" className="main-1-0-3-0-0">
                              <div className="main-navigationlink_instance-1">
                                  <Navigationlink text={"Home"} /> 
                              </div>
                          </a>
                      </div>
                  </div>
                  <div className="main-1-0-4">
                      <div className="main-1-0-4-0">
                          <a href="#work" className="main-1-0-4-0-0">
                              <div className="main-navigationlink_instance-3">
                                  <Navigationlink text={"Work"} /> 
                              </div>
                          </a>
                      </div>
                  </div>
                  <div className="main-1-0-5">
                      <div className="main-1-0-5-0">
                          <a href="#speaking" className="main-1-0-5-0-0">
                              <div className="main-navigationlink_instance-2">
                                  <Navigationlink text={"Speaking"} /> 
                              </div>
                          </a>
                      </div>
                  </div>
                  <div className="main-1-0-6">
                      <div className="main-1-0-6-0">
                          <a href="#references" className="main-1-0-6-0-0">
                              <div className="main-navigationlink_instance-16">
                                  <Navigationlink text={"References"} /> 
                              </div>
                          </a>
                      </div>
                  </div>
                  <div className="main-1-0-7">
                      <div className="main-1-0-7-0">
                          <a href="#writing" className="main-1-0-7-0-0">
                              <div className="main-navigationlink_instance-12">
                                  <Navigationlink text={"Writing"} /> 
                              </div>
                          </a>
                      </div>
                  </div>
                  <div className="main-1-0-8">
                      <div className="main-1-0-8-0">
                          <a href="#contact" className="main-1-0-8-0-0">
                              <div className="main-navigationlink_instance-0">
                                  <Navigationlink text={"Contact"} /> 
                              </div>
                          </a>
                      </div>
                  </div>
              </div>
              <div className="main-1-1">
                  <div className="main-line-9" /> 
              </div>
              <div className="main-1-2">
                  <div className="main-1-2-0">
                      <div className="main-1-2-0-0">
                          <div className="main-marcus_ellison_-0">
                              Marcus Ellison
                          </div>
                      </div>
                      <div className="main-1-2-0-1">
                          <div className="main-entrepreneur_maker_coder_-0">
                              <div>Entrepreneur</div>
                              <div>Maker</div>
                              <div>Coder </div>
                          </div>
                      </div>
                  </div>
                  <img src="https://ucarecdn.com/00872b5e-826c-40ee-b368-b9bd8ef10ed5/" className="main-hero-image-8" /> 
              </div>
              <div className="main-1-3">
                  <div className="main-rectangle_4">
                      <div className="main-1-3-0-0">
                          <div className="main-why_-5">WHY</div>
                      </div>
                      <div className="main-1-3-0-1">
                          <div className="main-life_has_a_purpose_you_are_that_purpose_-8">
                              Life has a purpose. You are that purpose. 
                          </div>
                      </div>
                      <div className="main-1-3-0-2">
                          <div className="main-workanchor-3"><div id="work" /></div>
                      </div>
                      <div className="main-1-3-0-3">
                          <div className="main-work_-1">WORK</div>
                      </div>
                  </div>
              </div>
              <div className="main-1-4">
                  <div className="main-rectangle_5">
                      <div className="main-1-4-0-0">
                          <div className="main-work-image-19">
                              <div className="main-1-4-0-0-0-0">
                                  <div className="main-in_stealth_-9">In Stealth</div>
                              </div>
                          </div>
                          <div className="main-rectangle-8">
                              <div className="main-1-4-0-0-1-0">
                                  <div className="main-venturemark_-7">VentureMark</div>
                              </div>
                              <div className="main-1-4-0-0-1-1">
                                  <div className="main-founder_ceo_product_development_-1">
                                      {"FOUNDER | CEO  | PRODUCT & DEVELOPMENT"}
                                  </div>
                              </div>
                              <div className="main-1-4-0-0-1-2">
                                  <div className="main-in_private_beta_venturemark_organizes_investments_and_relationships_for_angel_investors_around_the_world_no_data_entry_required_-7">
                                      In private beta. VentureMark organizes investments and relationships for angel investors around the world. No data entry required.
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="main-1-4-0-1">
                          <div className="main-rectangle-02">
                              <div className="main-1-4-0-1-0-0">
                                  <div className="main-hackerfleet_-5">HackerFleet</div>
                              </div>
                              <div className="main-1-4-0-1-0-1">
                                  <div className="main-co-founder_ceo_-6">
                                      {"CO-FOUNDER | CEO"}
                                  </div>
                              </div>
                              <div className="main-1-4-0-1-0-2">
                                  <div className="main-innovation_studio_in_vietnam_profitable_within_3_">
                                      Innovation studio in Vietnam. Profitable within 3 months. We held two events per month on product innovation and helped companies solve tech and product challenges in Singapore and San Francisco.
                                  </div>
                              </div>
                          </div>
                          <div className="main-work-image-53" /> 
                      </div>
                      <div className="main-1-4-0-2">
                          <div className="main-work-image-3">
                              <ReactPlayer url='https://venturemark.wistia.com/medias/o14g94ib3j' />
                          </div>
                          <div className="main-rectangle-2">
                              <div className="main-1-4-0-2-1-0">
                                  <div className="main-coderschool_-7">CoderSchool</div>
                              </div>
                              <div className="main-1-4-0-2-1-1">
                                  <div className="main-co-founder_business_development_-3">
                                      {"CO-FOUNDER |  BUSINESS DEVELOPMENT"}
                                  </div>
                              </div>
                              <div className="main-1-4-0-2-1-2">
                                  <div className="main-coding_school_in_vietnam_grew_community_reaching_thousands_of_engineers_and_dozens_of_companies_negotiated_and_closed_first_40">
                                      Coding school in Vietnam. Grew community reaching thousands of engineers and dozens of companies. Negotiated and closed first $40,000 in revenue. Created and managed pre-accelerator pilot program.
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="main-1-4-0-3">
                          <div className="main-rectangle-23">
                              <div className="main-1-4-0-3-0-0">
                                  <div className="main-wurk_happy_-6">Wurk Happy</div>
                              </div>
                              <div className="main-1-4-0-3-0-1">
                                  <div className="main-co-founder_ceo_product_frontend_development_-0">
                                      {"CO-FOUNDER |  CEO | PRODUCT & FRONTEND DEVELOPMENT"}
                                  </div>
                              </div>
                              <div className="main-1-4-0-3-0-2">
                                  <div className="main-b2b">
                                      B2B SaaS for freelancers. Raised $140k angel. Users could create agreements, invoice, receive payment, and deposit funds securely into their bank account in a simple interface.
                                  </div>
                              </div>
                          </div>
                          <div className="main-work-image-16">
                              <ReactPlayer url='https://venturemark.wistia.com/medias/2yhst8uig3' />
                          </div>
                      </div>
                      <div className="main-1-4-0-4">
                          <div className="main-work-image-36" /> 
                          <div className="main-rectangle-21">
                              <div className="main-1-4-0-4-1-0">
                                  <div className="main-saulter_ellison_-4">
                                      {"Saulter & Ellison"}
                                  </div>
                              </div>
                              <div className="main-1-4-0-4-1-1">
                                  <div className="main-co-founder_-6">CO-FOUNDER </div>
                              </div>
                              <div className="main-1-4-0-4-1-2">
                                  <div className="main-syndicated_commercial_real_estate_opportunities_in_new_york_city_with_anthony_leichter_and_axel_stawski_we_got_a_20">
                                      Syndicated Commercial Real Estate Opportunities in New York City with Anthony Leichter and Axel Stawski. We got a $20 million opportunity under contract and secured funds for acquisition and development.
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-1-5">
                  <div className="main-speakinganchor-7">
                      <div id="speaking" />
                  </div>
              </div>
              <div className="main-1-6">
                  <div className="main-rectangle_9">
                      <div className="main-1-6-0-0">
                          <div className="main-speaking_-2">SPEAKING</div>
                      </div>
                      <div className="main-1-6-0-1">
                          <div className="main-1-6-0-1-0">
                              <div className="main-1-6-0-1-0-0">
                                  <div className="main-philippines_interview-3">
                                      <iframe width="320" height="200" src="https://www.youtube.com/embed/m9kybxMjDBI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                                  </div>
                              </div>
                          </div>
                          <div className="main-1-6-0-1-1">
                              <div className="main-1-6-0-1-1-0">
                                  <div className="main-philippines_interview-0" /> 
                              </div>
                          </div>
                          <div className="main-1-6-0-1-2">
                              <div className="main-1-6-0-1-2-0">
                                  <div className="main-philippines_interview-1" /> 
                              </div>
                          </div>
                      </div>
                      <div className="main-1-6-0-2">
                          <div className="main-philippines_-3">Philippines</div>
                          <div className="main-_singapore_-7"> Singapore</div>
                          <div className="main-vietnam_-6">Vietnam</div>
                      </div>
                  </div>
              </div>
              <div className="main-1-7">
                  <div className="main-referencesanchor-1">
                      <div id="references" />
                  </div>
              </div>
              <div className="main-1-8">
                  <div className="main-1-8-0" /> 
                  <div className="main-rectangle_2">
                      <div className="main-1-8-1-0">
                          <div className="main-references_-9">REFERENCES</div>
                      </div>
                      <div className="main-1-8-1-1">
                          <div className="main-_marcus_and_i_went_to_nyu_together_he_s_a_super_smart_entrepreneur_with_big_ideas_and_fine_execution_i_often_believe_in_backing_people_over_ideas_marcus_is_a_perfect_example_of_the_type_of_person_i_would_back_even_without_an_idea_-5">
                              {"\" Marcus and I went to NYU together. He's a super smart entrepreneur with big ideas and fine execution. I often believe in backing people over ideas. Marcus is a perfect example of the type of person I would back (even without an idea)! \" "}
                          </div>
                      </div>
                      <div className="main-1-8-1-2">
                          <a href="https://www.linkedin.com/in/brycemaddock/" target="_blank" className="main-1-8-1-2-0">
                              <div className="main-bryce_maddock_-3">BRYCE MADDOCK</div>
                          </a>
                      </div>
                      <div className="main-1-8-1-3">
                          <div className="main-ceo_co-founder_-50">
                              {"CEO | Co-Founder, "}
                          </div>
                          <a href="https://www.taskus.com/" target="_blank" className="main-1-8-1-3-1">
                              <div className="main-referencelink_instance-16">
                                  <Referencelink text={"TaskUs"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-8-1-4">
                          <div className="main-referencelink_instance-8">
                              <Referencelink text={"Valued at over $500M "} /> 
                          </div>
                      </div>
                      <div className="main-1-8-1-5">
                          <div className="main-_marcus_is_a_thoughtful_collaborator_a_philosopher_in_developer_s_shoes_he_strives_to_understand_the_undercurrents_of_what_he_makes_a_key_component_to_creating_things_full_of_meaning_working_with_him_is_a_joy_-2">
                              {"\"Marcus is a thoughtful collaborator—a philosopher in developer's shoes. He strives to understand the undercurrents of what he makes, a key component to creating things full of meaning. Working with him is a joy.\""}
                          </div>
                      </div>
                      <div className="main-1-8-1-6">
                          <a href="https://www.linkedin.com/in/joeycofone/" target="_blank" className="main-1-8-1-6-0">
                              <div className="main-joey_cofone_-2">JOEY COFONE</div>
                          </a>
                      </div>
                      <div className="main-1-8-1-7">
                          <div className="main-ceo_co-founder_-0">
                              {"CEO | Co-Founder,"}
                          </div>
                          <a href="https://www.baronfig.com/" target="_blank" className="main-1-8-1-7-1">
                              <div className="main-referencelink_instance-7">
                                  <Referencelink text={"Baron Fig"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-8-1-8">
                          <a href="http://joeycofone.com/about/" target="_blank" className="main-1-8-1-8-0">
                              <div className="main-referencelink_instance-3">
                                  <Referencelink text={"Award winning designer"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-8-1-9">
                          <div className="main-_marcus_is_a_fellow_startup_founder_i_ve_met_with_a_few_times_in_nyc_who_is_serious_determined_and_extremely_smart_i_ve_watched_him_build_up_wurk_happy_from_idea_stage_to_design_mockup_to_product_and_he_knows_how_to_get_things_done_-6">
                              {"\"Marcus is a fellow startup founder I've met with a few times in NYC who is serious, determined, and extremely smart. I've watched him build up Wurk Happy from idea stage to design mockup to product, and he knows how to get things done.\""}
                          </div>
                      </div>
                      <div className="main-1-8-1-10">
                          <a href="https://www.linkedin.com/in/andrewmontalenti/" target="_blank" className="main-1-8-1-10-0">
                              <div className="main-andrew_montalenti_-6">
                                  ANDREW MONTALENTI
                              </div>
                          </a>
                      </div>
                      <div className="main-1-8-1-11">
                          <div className="main-cto_co-founder_-8">
                              {"CTO | Co-Founder, "}
                          </div>
                          <a href="https://www.parse.ly/" target="_blank" className="main-1-8-1-11-1">
                              <div className="main-referencelink_instance-87">
                                  <Referencelink text={"Parse.ly"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-8-1-12">
                          <a href="https://blog.parse.ly/post/6282/why-we-said-no-vc-money/" target="_blank" className="main-1-8-1-12-0">
                              <div className="main-referencelink_instance-26">
                                  <Referencelink text={"Turned down $40 million investment offer"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-8-1-13">
                          <div className="main-_amazing_and_large_underserved_space_that_needs_better_aggregation_platforms_and_technology_marcus_and_team_wurk_happy_are_winners_and_the_technical_talent_is_also_strong_looking_forward_to_their_inevitable_sucess_with_the_correct_financial_partners_-5">
                              {"\"Amazing and large underserved space that needs better aggregation platforms and technology. Marcus and team [Wurk Happy] are winners and the technical talent is also strong. Looking forward to their inevitable sucess with the correct financial partners....\""}
                          </div>
                      </div>
                      <div className="main-1-8-1-14">
                          <a href="https://www.linkedin.com/in/davidolk/" target="_blank" className="main-1-8-1-14-0">
                              <div className="main-david_olk_-1">DAVID OLK</div>
                          </a>
                      </div>
                      <div className="main-1-8-1-15">
                          <div className="main-coo_co-founder_-6">
                              {"COO | Co-Founder,"}
                          </div>
                          <a href="https://www.shopkeep.com/" target="_blank" className="main-1-8-1-15-1">
                              <div className="main-referencelink_instance-63">
                                  <Referencelink text={"ShopKeep"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-8-1-16">
                          <a href="https://venturebeat.com/2015/07/28/shopkeep-focuses-on-growth-with-60-million-in-series-d-funding/" target="_blank" className="main-1-8-1-16-0">
                              <div className="main-referencelink_instance-12">
                                  <Referencelink text={"Raised over $100M"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-8-1-17">
                          <div className="main-_working_with_marcus_is_always_a_pleasure_as_he_is_an_engineer_who_builds_things_from_first_principles_when_they_are_truly_needed_and_doesn_t_get_carried_away_with_the_current_fads_plus_he_s_just_a_genuinely_nice_guy_-4">
                              {"\"Working with Marcus is always a pleasure as he is an engineer who builds things from first principles when they are truly needed, and doesn’t get carried away with the current fads. Plus, he’s just a genuinely nice guy.\""}
                          </div>
                      </div>
                      <div className="main-1-8-1-18">
                          <a href="https://www.linkedin.com/in/theodorewyly/" target="_blank" className="main-1-8-1-18-0">
                              <div className="main-teddy_wyly_-4">TEDDY WYLY</div>
                          </a>
                      </div>
                      <div className="main-1-8-1-19">
                          <div className="main-software_engineer_-1">
                              Software Engineer,
                          </div>
                          <a href="https://www.apple.com/" target="_blank" className="main-1-8-1-19-1">
                              <div className="main-referencelink_instance-54">
                                  <Referencelink text={"Apple"} /> 
                              </div>
                          </a>
                      </div>
                  </div>
                  <div className="main-1-8-2" /> 
              </div>
              <div className="main-1-9">
                  <div className="main-writinganchor-5">
                      <div id="writing" />
                  </div>
              </div>
              <div className="main-1-10">
                  <div className="main-1-10-0" /> 
                  <div className="main-rectangle_1">
                      <div className="main-1-10-1-0">
                          <div className="main-writing_-6">WRITING</div>
                      </div>
                      <div className="main-1-10-1-1">
                          <a href="https://medium.com/venturemark/wework-southeast-asia-3c5870433a9c" target="_blank" className="main-1-10-1-1-0">
                              <div className="main-bloglink_instance-4">
                                  <Bloglink text={"WeWork and the Disruption of Southeast Asian Real Estate"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-10-1-2">
                          <a href="https://medium.com/venturemark/broken-5985e175ae62" target="_blank" className="main-1-10-1-2-0">
                              <div className="main-bloglink_instance-6">
                                  <Bloglink text={"Investing in Southeast Asian Startups is Broken"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-10-1-3">
                          <a href="https://blog.hackerfleet.com/how-the-worlds-best-companies-build-new-products-dc4092300689" target="_blank" className="main-1-10-1-3-0">
                              <div className="main-bloglink_instance-1">
                                  <Bloglink text={"How the World’s Best Companies Build New Products"} /> 
                              </div>
                          </a>
                      </div>
                      <div className="main-1-10-1-4">
                          <div className="main-bloglink_instance-49">
                              <Bloglink text={"Dear Young Talent"} /> 
                          </div>
                      </div>
                  </div>
                  <div className="main-1-10-2" /> 
              </div>
              <div className="main-1-11">
                  <div className="main-contactanchor-3">
                      <div id="contact" />
                  </div>
              </div>
              <div className="main-1-12">
                  <div className="main-rectangle_11">
                      <div className="main-1-12-0-0">
                          <div className="main-contact_-5">CONTACT</div>
                      </div>
                      <div className="main-1-12-0-1">
                          <div className="main-please_contact_me_if_you_are_exceptional_or_strive_to_be_-8">
                              Please contact me if you are exceptional. Or strive to be.
                          </div>
                      </div>
                      <div className="main-1-12-0-2">
                          <div className="main-marcus_dot_ellison_at_gmail_dot_com_-5">
                              {"marcus [dot] ellison [at] gmail [dot] com"}
                          </div>
                      </div>
                  </div>
              </div>
              <div className="main-1-13">
                  <div className="main-line-2" /> 
              </div>
              <div className="main-1-14">
                  <div className="main-rectangle_3">
                      <div className="main-1-14-0-0">
                          <div className="main-marcus_ellison_-4">
                              Marcus Ellison
                          </div>
                      </div>
                      <div className="main-1-14-0-1">
                          <div className="main-globally_crafted_copyright_20">
                              Globally crafted. Copyright 2018.
                          </div>
                      </div>
                      <div className="main-1-14-0-2">
                          <a href="https://www.producthunt.com/@marcojelli" target="_blank" className="main-1-14-0-2-0">
                              <div className="main-image-96" /> 
                          </a>
                          <a href="https://twitter.com/marcojelli" target="_blank" className="main-1-14-0-2-1">
                              <div className="main-image-03" /> 
                          </a>
                          <a href="https://github.com/marcusellison" target="_blank" className="main-1-14-0-2-2">
                              <div className="main-image-5" /> 
                          </a>
                          <a href="https://www.linkedin.com/in/marcusellison/" target="_blank" className="main-1-14-0-2-3">
                              <div className="main-image-38" /> 
                          </a>
                          <a href="https://example.cohttps://www.instagram.com/sixwordsofpoetry" target="_blank" className="main-1-14-0-2-4">
                              <div className="main-image-36" /> 
                          </a>
                      </div>
                  </div>
              </div>
              <div className="main-1-15" /> 
          </div>
      </div>
    );
  }
};
