// Generated by https://pagedraw.io/pages/11698
import React from 'react';
import './navigationlink.css';


export default class Navigationlink extends React.Component {
  render() {
    return (
      <div className="pd-onhover-parent navigationlink">
          { (("default") === "default") ?
              <div className="navigationlink-default-2">
                  <div className="navigationlink-0-0-0">
                      <div className="navigationlink-link_-1">
                          { this.props.text }
                      </div>
                  </div>
              </div>
          : null}
          <div className="pd-onhover navigationlink-default_hover-5">
              <div className="navigationlink-1-0">
                  <div className="navigationlink-link_-8">
                      { this.props.text }
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
