// Generated by https://pagedraw.io/pages/11698
import React from 'react';
import './referencelink.css';


export default class Referencelink extends React.Component {
  render() {
    return (
      <div className="pd-onhover-parent referencelink">
          { (("default") === "default") ?
              <div className="referencelink-default-0">
                  <div className="referencelink-0-0-0">
                      <div className="referencelink-link_-9">
                          { this.props.text }
                      </div>
                  </div>
              </div>
          : null}
          <div className="pd-onhover referencelink-default_hover-1">
              <div className="referencelink-1-0">
                  <div className="referencelink-link_-8">
                      { this.props.text }
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
